modLoader = "kotlinforforge"
loaderVersion = "${loaderVersionRange}"
#issueTrackerURL = ""
license = "${modLicense}"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthors}"
description = '''
${modDescription}
'''
logoFile = "logo.png"

[[dependencies.${modId}]]
modId = "forge"
mandatory = true
versionRange = "${forgeVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"
