# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
modVersion=1.4.0
modGroupId=io.github.cotrin8672
modId=itemindicator
modName=Item Indicator
modAuthors=Cotrin
modLicense=MIT
modDescription=This mod shows detail information of some items.
enabledPlatforms=fabric,neoforge
