[versions]
loom = "1.7-SNAPSHOT"
architecturyPlugin = "3.4-SNAPSHOT"
shadow = "8.1.1"
minecraft = "1.21.3"
minecraftRange = "[1.21.3, 1.22)"
neoforge = "21.3.66"
neoforgeRange = "[21.3,)"
fabricLoader = "0.16.7"
fabricApi = "0.114.0+1.21.3"
fabricKotlin = "1.12.3+kotlin.2.0.21"
kotlin = "2.0.21"
kotlinforforge = "5.7.0"
kotlinforforgeRange = "[5.5,)"
modPublisher = "2.1.6"
clothConfig = "16.0.143"
modmenu = "12.0.0"

[libraries]
minecraft = { module = "net.minecraft:minecraft", version.ref = "minecraft" }
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabricKotlin" }
kotlinforforge = { module = "thedarkcolour:kotlinforforge-neoforge", version.ref = "kotlinforforge" }
clothConfig-neoforge = { module = "me.shedaniel.cloth:cloth-config-neoforge", version.ref = "clothConfig" }
clothConfig-fabric = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "clothConfig" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

[plugins]
loom = { id = "dev.architectury.loom", version.ref = "loom" }
architectury = { id = "architectury-plugin", version.ref = "architecturyPlugin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
modPublisher = { id = "com.hypherionmc.modutils.modpublisher", version.ref = "modPublisher" }
