[versions]
loom = "1.9-SNAPSHOT"
architecturyPlugin = "3.4-SNAPSHOT"
shadow = "8.1.1"
minecraft = "1.20.1"
minecraftRange = "[1.20.1, 1.21)"
forge = "1.20.1-47.3.0"
forgeRange = "[1.20.1-47.3.0,)"
fabricLoader = "0.16.5"
fabricApi = "0.92.2+1.20.1"
fabricKotlin = "1.11.0+kotlin.2.0.0"
kotlin = "2.0.0"
kotlinforforge = "4.11.0"
kotlinforforgeRange = "[4.10,)"
modPublisher = "2.1.6"
clothConfig = "11.1.136"
modmenu = "7.2.2"

[libraries]
minecraft = { module = "net.minecraft:minecraft", version.ref = "minecraft" }
forge = { module = "net.minecraftforge:forge", version.ref = "forge" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabricKotlin" }
kotlinforforge = { module = "thedarkcolour:kotlinforforge", version.ref = "kotlinforforge" }
clothConfig-forge = { module = "me.shedaniel.cloth:cloth-config-forge", version.ref = "clothConfig" }
clothConfig-fabric = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "clothConfig" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

[plugins]
loom = { id = "dev.architectury.loom", version.ref = "loom" }
architectury = { id = "architectury-plugin", version.ref = "architecturyPlugin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
modPublisher = { id = "com.hypherionmc.modutils.modpublisher", version.ref = "modPublisher" }
